### PR TITLE
feat: Add and bundle backend

### PR DESCRIPTION
**Pull request by faucomte97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-service-template/1)

### CODE REVIEW

**Comment by SKairinos** [comment]
@faucomte97, I was unable to run the script:
```txt
[Error: ENOENT: no such file or directory, open '/home/skairinos/Repositories/codeforlife-workspace/codeforlife-service-template/backend/myapp/templates/my_app_react.html'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/skairinos/Repositories/codeforlife-workspace/codeforlife-service-template/backend/myapp/templates/my_app_react.html'
}
Internal Server Error: /
Traceback (most recent call last):
  File "/home/skairinos/.local/share/virtualenvs/codeforlife-service-template-u1SKqjWR/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/skairinos/.local/share/virtualenvs/codeforlife-service-template-u1SKqjWR/lib/python3.11/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skairinos/Repositories/codeforlife-workspace/codeforlife-service-template/backend/myapp/views.py", line 5, in render_react
    return render(request, "my_app_react.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skairinos/.local/share/virtualenvs/codeforlife-service-template-u1SKqjWR/lib/python3.11/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skairinos/.local/share/virtualenvs/codeforlife-service-template-u1SKqjWR/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skairinos/.local/share/virtualenvs/codeforlife-service-template-u1SKqjWR/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: my_app_react.html
[24/Mar/2023 17:06:55] "GET / HTTP/1.1" 500 80299
```

**Comment by SKairinos** [comment]
@faucomte97, some further feedback:
- [x] Pipfile and Pipfile.lock ot be moved to the backend directory.
- [x] update run script to "pipenv install --dev" in backend directory
- [x] update run script to "npm install" in frontend directory.
- [x] update run script to "npm run build" in frontend directory.

**Comment by SKairinos** [comment]
@faucomte97, you also need to fix [this path](https://github.com/ocadotechnology/codeforlife-service-template/blob/113c98aeaf2967b781070e0119875d34c46015d2/frontend/.eslintrc.json#L14) to be "frontend/tsconfig.json"

**Review by faucomte97 — COMMENTED** [review]
Done and should work - except the path because I don't seem to need it :man_shrugging: 

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-service-template/1#-:-NSAikp3EnDMtbGFNeFf:biw7va0)* status: 0 of 59 files reviewed, all discussions resolved (waiting on @faucomte97)

**Review by SKairinos — APPROVED** [review]
> Reviewed 48 of 56 files at r1, 3 of 7 files at r2, 1 of 2 files at r3, 5 of 5 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-service-template/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Pull request merged**
